# Generated by Django 3.1.3 on 2021-04-12 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('discription', models.TextField(max_length=135)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='')),
                ('featured', models.BooleanField()),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.authors')),
                ('categories', models.ManyToManyField(to='magazin.Category')),
            ],
        ),
    ]
