# Generated by Django 3.1.3 on 2021-04-05 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('job_description', models.TextField(max_length=135)),
                ('skill_requirement', models.TextField(max_length=135)),
                ('additional_information', models.TextField(max_length=135)),
                ('how_to_apply', models.TextField(max_length=135)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vcount', models.IntegerField(default=0)),
                ('logo', models.ImageField(upload_to='')),
                ('featured', models.BooleanField()),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('about', models.TextField(max_length=135)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('vcount', models.IntegerField(default=0)),
                ('banner', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('website', models.URLField(blank=True, max_length=195, null=True)),
                ('featured', models.BooleanField()),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('jobs', models.ManyToManyField(related_name='jb', to='jobs.Jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sd', to='jobs.studios'),
        ),
    ]
