# Generated by Django 3.1.3 on 2021-04-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='additional_information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='how_to_apply',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='skill_requirement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studios',
            name='about',
            field=models.TextField(),
        ),
    ]
