# Generated by Django 3.1.3 on 2021-04-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210405_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='studio',
        ),
    ]
