# Generated by Django 3.1.3 on 2021-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='country',
            field=models.CharField(default='usa', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='state',
            field=models.CharField(default='carlifonia', max_length=70),
            preserve_default=False,
        ),
    ]
