# Generated by Django 3.2 on 2021-05-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('item_created_date', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=1.0)),
                ('image', models.ImageField(upload_to='')),
                ('image_path', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('featured', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
