# Generated by Django 3.2 on 2021-05-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_category_tag_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.ManyToManyField(to='prints.Tags'),
        ),
        migrations.AddField(
            model_name='prints',
            name='category',
            field=models.ManyToManyField(to='prints.Category'),
        ),
        migrations.AddField(
            model_name='prints',
            name='tag',
            field=models.ManyToManyField(to='prints.Tags'),
        ),
    ]
