# Generated by Django 3.1.3 on 2021-04-10 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('discription', models.TextField(max_length=135)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('google', models.URLField(blank=True, max_length=195, null=True)),
                ('youtube', models.URLField(blank=True, max_length=195, null=True)),
                ('spotify', models.URLField(blank=True, max_length=195, null=True)),
                ('apple', models.URLField(blank=True, max_length=195, null=True)),
                ('soundcloud', models.URLField(blank=True, max_length=195, null=True)),
                ('featured', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
