# Generated by Django 3.1.3 on 2021-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='discription',
            field=models.TextField(max_length=400),
        ),
    ]
