# Generated by Django 3.1.3 on 2021-04-04 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_picture_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='dislikes',
            field=models.ManyToManyField(blank=True, null=True, related_name='pic_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='picture',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='pic_loved', to=settings.AUTH_USER_MODEL),
        ),
    ]
