# Generated by Django 3.1.3 on 2021-04-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_path',
            field=models.FileField(upload_to=''),
        ),
    ]
