# Generated by Django 3.1.3 on 2021-04-01 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('gender', models.TextField(choices=[('1', 'm'), ('0', 'f')], default='0')),
                ('profession', models.CharField(max_length=100)),
                ('city', models.CharField(default='New york', max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('date_of_birth', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
